server:
  port: 9999
  servlet:
    context-path: /api

spring:
  application:
    name: app

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/open_api
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 192.168.79.130
    port: 6379
    password: Pjh_2905231006     #密码
    database: 0
    timeout: 10000    #访问超时时间
    lettuce: #lettuce依赖commons-pool2, 所以要导入commons-pool2
      pool:
        max-active: 10  #连接池最大连接数  
        max-wait: 5000  #连接池最大等待阻塞时间
        max-idle: 10     #连接池中最大空闲连接数
        min-idle: 2     #连接池中最小空闲数

  session:
    store-type: redis
    timeout: 1800 # session失效时间(秒)

  # 配置日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #时间戳统一转换为指定格式
    time-zone: GMT+8  # 时区修改为东8区

management:
  endpoints:
    web:
      exposure:
        include: "*"

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(1-已删除 0-未删除)

knife4j:
  # 开启增强配置 
  enable: true
  # 为true则开启生产环境屏蔽
  production: false
  basic:
    enable: true # 此项设置为true表示开启账号密码验证
    username: admin # enable为true时对应的登陆账号
    password: admin # enable为true时对应的登陆密码    